Distlay/blog/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"


urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('tag/<slug:slug>/',views.tagged,name="tagged"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
    
    
]

Distlay/blog/ask/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "ask"


urlpatterns = [
    path('addquestion/',views.addQuestion,name="addquestion"),
    path('question/<int:id>',views.detail,name="detail"),
    path('tag/<slug:slug>/',views.tagged,name="tagged"),
    path('update-question/<int:id>',views.updateQuestion,name="update"),
    path('delete-question/<int:id>',views.deleteQuestion,name="remove"),
    path('answer/<int:id>',views.addAnswer,name="answer"),
    path('',views.questions,name="questions"),
    path('', views.AddReport,name="add_report"),

]

Distlay/blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/',include("ask.urls")),
    path('',views.index, name="index"),
    path('about/',views.about, name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="password_reset.html", html_email_template_name="password_reset_email.html" ), name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html") , name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),

    


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Distlay/blog/user/urls.py
from django.contrib import admin
from django.urls import path , reverse_lazy
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = "user"


urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('profile/',views.profileUser,name="profile"),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Distlay/blog/article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from taggit.managers import  TaggableManager

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete= models.CASCADE, verbose_name='Author')
    title = models.CharField(max_length=50, verbose_name="Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Created Date")
    slug = models.SlugField(unique=True,max_length=100, default=None)
    tags = TaggableManager()
    article_image = models.FileField(blank = True, null = True, verbose_name = "Upload Image")

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE, verbose_name = "Article",related_name="comments")
    comment_title = models.CharField(max_length=30, verbose_name = "Title", default=None)
    comment_author = models.ForeignKey(User,on_delete= models.CASCADE, verbose_name='User')
    comment_content = models.CharField(max_length=200,verbose_name="Comment")
    comment_date = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.comment_content
    
    class Meta:
        ordering = ['-comment_date']
    

Distlay/blog/article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","tags","article_image"]

Distlay/blog/article/views.py
from django.shortcuts import redirect, render,HttpResponse,get_object_or_404,reverse
from ask.models import Questions
from .forms import ArticleForm
from django.contrib import messages
from .models import Article as Article,Comment
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
from taggit.models import Tag
from django.core.paginator import Paginator


# Create your views here.

@login_required(login_url="user:login")
def articles(request):

    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles": articles})

    articles = Article.objects.all()
    paginator = Paginator(articles,2)

    page_number = request.GET.get('page',1)
    page_obj = paginator.get_page(page_number)

    return render(request,"articles.html",{"articles": page_obj.object_list,"page_obj":page_obj,"page_number":int(page_number)})

def index(request):
    context = {
        
    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")

def contact(request):
    return render(request,"contact.html")

@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author =request.user)
    questions = Questions.objects.filter(author=request.user)
    context = {

        "articles" : articles,
        "questions" : questions

    }
    
    return render(request,"dashboard.html",context)
    
@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    common_tags = Questions.tags.most_common()[:12]

    if form.is_valid():
        article = form.save(commit = False)
        article.slug = slugify(article.title)
        article.author = request.user
        article.save()
        form.save_m2m()

        messages.success(request,"Article created successfully!")
        return redirect("article:dashboard")


    context = {
        "form" : form,
        "common_tags" : common_tags,
    }
    return render(request,"addarticle.html",context)

def tagged(request,slug):
    tag = get_object_or_404(Tag, slug=slug)
    articles = Article.objects.filter(tags=tag)

    context = {
        "tag" : tag,
        "articles" : articles,
    }

    return render(request,"articles.html",context)

def tag_detail(request,slug):
    article = get_object_or_404(Article,slug=slug)
    return render(request,"articles.html",{"article":article})
    
@login_required(login_url="user:login")
def detail(request,id):
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
   

    return render(request,"detail.html",{"article":article,"comments":comments,})

@login_required(login_url="user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)

    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()

        messages.success(request,"Article updated successfully!")
        return redirect("article:dashboard")

    return render(request,"update.html",{"form":form})

@login_required(login_url="user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()

    messages.success(request,"Article deleted successfully!")

    return redirect("article:dashboard")


def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_title = request.POST.get('comment_title')
        comment_content = request.POST.get('comment_content')
        comment_author = request.user

        newComment = Comment(comment_title = comment_title, comment_content = comment_content, comment_author = comment_author)

        newComment.article = article

        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":str(id)}))

Distlay/blog/templates/add_category.html
{% extends "layout.html" %}

{% block body %}
  
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3 align="center">Add Category</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form | crispy }}

            <br>
            <button type="submit" class="btn btn-outline-info">Add</button>
           
        
        </form>
    </div>
  </div>



{% endblock body %}

Distlay/blog/templates/dashboard.html
{% extends "dashboard-layout.html" %}
{% load static %}

{% block body %}
  
      <!-- Page Wrapper -->
      <div id="wrapper">

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">
                  
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Articles <a class = "btn btn-outline-info" href = "/articles/addarticle">Add Article</a> </h6>
                        </div>
                        <div class="card-body">
                          {% if articles %}
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Author</th>
                                            <th>Date</th>
                                            <th>Update</th>
                                            <th>Delete</th>
                                        </tr>
                                    </thead>
                                    {% for article in articles %}
                                    <tbody>
                                        <tr>
                                            <td>{{article.id}}</td>
                                            <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
                                            <td>{{article.author.username}}</td>
                                            <td>{{article.created_date}}</td>
                                            <td><a href="/articles/update/{{article.id}}" class = "btn btn-success">Update</a></td>
                                            <td><a href="/articles/delete/{{article.id}}" class = "btn btn-danger">Delete</a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                        
                                </table>
                            </div>
                        </div>
                        {% else %}
                        <div class="alert alert-info">You do not have any published articles yet.</div>
                    <!-- /.container-fluid -->
                    </div>
                </div>
                {% endif %}
            </div>
            <!-- End of Main Content -->
        </div>

            <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

              <!-- Begin Page Content -->
              <div class="container-fluid">

                <!-- DataTales Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Questions <a class = "btn btn-outline-info" href = "/questions/addquestion">Ask Question</a></h6>
                    </div>
                    <div class="card-body">
                      {% if questions %}
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Author</th>
                                        <th>Date</th>
                                        <th>Update</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                  {% for question in questions %}
                                <tbody>
                                    <tr>
                                        <td>{{question.id}}</td>
                                        <td><a href="{% url 'ask:detail' question.id %}">{{question.title}}</a></td>
                                        <td>{{question.author.username}}</td>
                                        <td>{{question.asked_date}}</td>
                                        <td><a href="/questions/update-question/{{question.id}}" class = "btn btn-success">Update</a></td>
                                        <td><a href="/questions/delete-question/{{question.id}}" class = "btn btn-danger">Delete</a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="alert alert-info">You have no questions asked yet.</div>
            <!-- /.container-fluid -->
            </div>
            {% endif %}
        </div>
      </div>
        <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; FOSoftwareBlog 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <script src="https://kit.fontawesome.com/e427689c7c.js" crossorigin="anonymous"></script>

    {% endblock body %}
 
  

Distlay/blog/templates/detail.html
{% extends "layout.html" %}

{% block body %}
{% load  static %}
<link rel="stylesheet" href="{% static 'css/comments.css' %}">


<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">{{article.created_date}}, created by {{article.author.username}}</div>
                    <div style="display:flex">
                        {% for tag in article.tags.all %}
                        <a href="{% url 'article:tagged' tag.slug %}" class="mr-1 badge badge-info"#>{{tag}}</a>
                        {% endfor %}
                    </div>
                </header>
                <!-- Preview image figure-->
               {% if article.article_image %}
               <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
               {% endif %}
                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{article.content | safe}}</p>
                </section>
            </article>
            <h5>Comments ( {{comments.count}} ) :</h5>
            <hr>
            
            {% if comments %}

            <div class="container">
                <div class="row">
            
            {% for comment in comments  %}

            <div class="col-md-12">
                <div class="media g-mb-30 media-comment">
                    {% if comment.comment_author.profile.avatar %}
                    <img class="d-flex g-width-50 g-height-50 rounded-circle g-mt-3 g-mr-15" src="{{comment.comment_author.profile.avatar.url}}" alt="Image Description">
                    {% else %}
                    <img class="d-flex g-width-50 g-height-50 rounded-circle g-mt-3 g-mr-15" src="{% static 'images/default.jpg' %}" alt="Image Description">
                    {% endif %}
                    <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
                      <div class="g-mb-15">
                        <h6 class="h5 g-color-gray-dark-v1 mb-0">{{comment.comment_author}}</h6> 
                        <span class="g-color-gray-dark-v4 g-font-size-12">{{comment.comment_date}}</span>
                        <hr>
                      </div>
                     <h6>{{comment.comment_title}}</h6>
                      <p> {{comment.comment_content | safe}}</p>
                      <ul class="list-inline d-sm-flex my-0">
                        <li class="list-inline-item ml-auto">
                          <a class="u-link-v5 g-color-gray-dark-v4 g-color-primary--hover" href="#!">
                            <i class="fa fa-flag"></i>
                            Report
                          </a>
                        </li>
                      </ul>
                    </div>
                </div>
            </div>
        
            <hr>
              
            {% endfor %}
        </div>
    </div>
            {% else %}
            
            <div class = "alert alert-warning">
                There is no comment here. Leave first comment now !
            </div>

            {% endif %}
            

            <div class="card my-4">
                <h5 class="card-header">Leave a Comment</h5>
            <div class = "card-body">
            <form class="mb-4" method="post" action="{% url 'article:comment' article.id %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="formGroupExampleInput">Title</label>
                    <input name="comment_title" type="text" class="form-control" id="formGroupExampleInput" placeholder="Comment Title">
                  </div>
                  <label for="formGroupExampleInput">Comment</label>
                  <textarea name="comment_content" class="form-control" rows="3" placeholder="Leave a comment!"></textarea>
                <br>
            <button type="submit" class="btn btn-outline-info">Submit</button>
            </form>
        </div>

        <script src="//cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>
        <script>CKEDITOR.replace('comment_content', {
            removePlugins: 'sourcearea,about',   
        }
        )</script>
      

{% endblock body %}

Distlay/blog/templates/index.html
{% extends "layout.html" %}
{% load static %}



{% block body %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/carousel.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link rel="stylesheet" href="{% static 'css/ionicons.css' %}">
<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">


<main role="main">

    <div class="carousel slide" data-ride="carousel" id="carouselExampleIndicators">
      <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#carouselExampleIndicators"></li>
        <li data-slide-to="1" data-target="#carouselExampleIndicators"></li>
        <li data-slide-to="2" data-target="#carouselExampleIndicators"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img alt="First slide" class="d-block w-100" src="{% static 'images/slider1.jpg' %}">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="animated bounceInRight" style="animation-delay: 1s">Distlay On The Air!</h5>
            <p class="animated bounceInLeft" style="animation-delay: 2s">
              The right layer to gain industry knowledge about software, learn new things and share your knowledge.</p>
              {% if request.user.is_authenticated %}
                
              {% else %}
              <p class="animated bounceInRight" style="animation-delay: 3s"><a href="{% url 'user:register' %}">Register Now</a></p> 
              {% endif %}
          </div>
        </div>
        <div class="carousel-item">
          <img alt="Second slide" class="d-block w-100" src="{% static 'images/slider2.jpg' %}">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="animated slideInDown" style="animation-delay: 1s">Are you a developer?</h5>
            <p class="animated fadeInUp" style="animation-delay: 2s">You can support the open source methodology by transferring your knowledge to other developers. Remember, we are the ones who will shape the world.</p>
            <p class="animated zoomIn" style="animation-delay: 3s"><a href="{% url 'article:articles' %}" target="_blank" >Software Articles</a></p>
          </div>
        </div>
        <div class="carousel-item">
          <img alt="Third slide" class="d-block w-100" src="{% static 'images/slider3.jpg' %}">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="animated zoomIn" style="animation-delay: 1s">Let's make the world open source</h5>
            <p class="animated fadeInLeft" style="animation-delay: 2s">
              If we decode the world's code and put it together like a puzzle, we can create our own world!</p>
            <p class="animated zoomIn" style="animation-delay: 3s"><a href="https://en.wikipedia.org/wiki/Open_source" target="_blank" >What is the open source?</a></p>
          </div>
        </div>
      </div><a class="carousel-control-prev" data-slide="prev" href="#carouselExampleIndicators" role="button"><span aria-hidden="true" class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a class="carousel-control-next" data-slide="next" href="#carouselExampleIndicators" role="button"><span aria-hidden="true" class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js">
    </script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js">
    </script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js">
    </script>
    
</main>

    <!-- 
    ================================================== -->

    <section id="services" class="section-bg">
      <div class="container">

        <header class="section-header">
          <h3 align="center">Distlay</h3>
          <p align="center">Distlay is a software community where you can find articles related to the software and ask your questions.Join us now to improve our community of sharing your knowledge.</p>
        </header>
        <br><br>
        <div class="row">
          <div class="col-md-6 col-lg-5 offset-lg-1 wow bounceInUp" data-wow-duration="1.4s">
            <div class="box">
              <div class="icon"><i class="ion-ios-people-outline" ></i></div>
              <h4 class="title"><a href="{% url 'user:register' %}">Join Our Community</a></h4>
              <p class="description">Register now and become a part of our community. Share your knowledge and improve yourself.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-5 wow bounceInUp" data-wow-duration="1.4s">
            <div class="box">
              <div class="icon"><i class="ion-code-working" style="color: #e9bf06;"></i></div>
              <h4 class="title"><a href="">Develop your projects</a></h4>
              <p class="description">Need more information for your project?. Study software articles and improve yourself. Lead your project.</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-5 offset-lg-1 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="box">
              <div class="icon"><i class="ion-ios-help" style="color: #3fcdc7;"></i></div>
              <h4 class="title"><a href="">Ask the Question</a></h4>
              <p class="description">You need some help? Immediately ask the question and wait for the answer from the experts of the topic.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-5 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
            <div class="box">
              <div class="icon"><i class="ion-ios-compose-outline" style="color:#41cf2e;"></i></div>
              <h4 class="title"><a href="">Share Your Knowledge</a></h4>
              <p class="description">Are you knowledgeable about software?. Share your knowledge with our community and contribute to the growth of our community.</p>
            </div>
          </div>

          <div class="col-md-6 col-lg-5 offset-lg-1 wow bounceInUp" data-wow-delay="0.2s" data-wow-duration="1.4s">
            <div class="box">
              <div class="icon"><i class="ion-ios-lightbulb-outline" style="color: #ff9205;"></i></div>
              <h4 class="title"><a href="">Share Your Ideas</a></h4>
              <p class="description">Share your ideas and find yourself teammates. Move your project to the next level. Contribute to our community.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-5 wow bounceInUp" data-wow-delay="0.2s" data-wow-duration="1.4s">
            <div class="box">
              <div class="icon"><i class="ion-ios-paper-outline" style="color: #4680ff;"></i></div>
              <h4 class="title"><a href="">Access to Articles</a></h4>
              <p class="description">Get access to software articles written by expert developers and increase your knowledge. That's how simple it is to develop.</p>
            </div>
          </div>

        </div>

      </div>
    </section>
<!-- #services -->
</div>

<hr>
<br>
<footer id="footer" class="top-space">

    <div class="footer1">
        <div class="container">
            <div class="row">
                
                <div class="col-md-3 widget">
                    <h4 class="widget-title">Contact</h4>
                    <div class="widget-body">
                        <p>Email:<br>
                            <a href="mailto:info@distlay.com">info@distlay.com</a><br>
                            <br>
                            Istanbul City, Turkey ZC 34513
                        </p>	
                    </div>
                </div>
                <div class="col-md-3 widget">
                    <h4 class="widget-title">Follow Us</h4>
                    <div class="widget-body">
                        <p class="follow-me-icons">
                            <a href="#" class="fa fa-twitter"></a>
                            <a href="#" class="fa fa-linkedin"></a>
                            <a href="#" class="fa fa-github"></a>
                            <a href="#" class="fa fa-instagram"></a>
                        </p>	
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <h4 class="widget-title">Distlay</h4>
                    <div class="widget-body">
                        <p>Distlay is where you can access open source codes, articles about software and provide information about your area of ​​expertise.</p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

    <div class="footer2">
        <div class="container">
            <div class="row">
                
                <div class="col-md-6 widget">
                    <div class="widget-body">
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="text-right">
                            Copyright &copy; 2021, Distlay. Developed by <a href="https://www.linkedin.com/in/p0zn/" rel="designer">Furkan OZKAN</a> 
                        </p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

</footer>	

{% endblock body %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>

Distlay/blog/templates/login.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}
{% load crispy_forms_tags %}

<div style="text-align: center;">
<img src="{% static 'images/content-logo.png' %}" widht="75px" height="75px"  alt="fosoftwareblog">
</div>
<br>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{form | crispy }}
            <button type="submit" class="btn btn-outline-info">Login</button>
        </form>
        <br>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'user:register' %}">Sign Up Now</a>
            </small>
            &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
            <small class="text-muted">
                Forgot Password? <a class="ml-2" href="{% url 'password_reset' %}">Reset Now</a>
            </small>
        </div>
    </div>
  </div>



{% endblock body %}

Distlay/blog/templates/update.html
{% extends "layout.html" %}

{% block body %}
  
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Article</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{form.media}}
            {{form | crispy }}


            <br>
            <button type="submit" class="btn btn-success">Update</button>
        
        </form>
    </div>
  </div>



{% endblock body %}