Distlay/blog/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"


urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('article/<int:id>',views.detail,name="detail"),
    path('tag/<slug:slug>/',views.tagged,name="tagged"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
    
    
]

Distlay/blog/ask/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "ask"


urlpatterns = [
    path('addquestion/',views.addQuestion,name="addquestion"),
    path('question/<int:id>',views.detail,name="detail"),
    path('tag/<slug:slug>/',views.tagged,name="tagged"),
    path('update-question/<int:id>',views.updateQuestion,name="update"),
    path('delete-question/<int:id>',views.deleteQuestion,name="remove"),
    path('answer/<int:id>',views.addAnswer,name="answer"),
    path('',views.questions,name="questions"),
    path('', views.AddReport,name="add_report"),

]

Distlay/blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/',include("ask.urls")),
    path('',views.index, name="index"),
    path('about/',views.about, name="about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="password_reset.html", html_email_template_name="password_reset_email.html" ), name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html") , name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),

    


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Distlay/blog/user/urls.py
from django.contrib import admin
from django.urls import path , reverse_lazy
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = "user"


urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('profile/',views.profileUser,name="profile"),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Distlay/blog/templates/includes/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">

<nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
    <a class="navbar-brand" href="/"><img class="logo" src="{% static 'images/test.png' %}" alt="Distlay"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}"><i class="fas fa-home"></i>&ensp;Home</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:articles' %}"><i class="fas fa-file-code"></i>&ensp;Software Articles</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'ask:questions' %}"><i class="fas fa-question-circle"></i>&ensp;Questions</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}"><i class="fas fa-book-reader"></i>&ensp;About</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}

       <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:profile' %}"><img width="20" height="20" src="{% static 'images/default-profile.png' %}" alt="User">&nbsp;&nbsp;{{request.user.username}}</a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'article:dashboard' %}"><i class="fas fa-columns"></i>&ensp;Dashboard</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:logout' %}"><i class="fas fa-sign-out-alt"></i>&ensp;Logout</a>
      </li>
      <li class="nav-item active">
          
        {% else %}

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:login' %}"><i class="fas fa-user"></i>&ensp;Login</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:register' %}"><i class="fas fa-sign-in-alt"></i>&ensp;Register</a>
        </li>
          
        {% endif %}
      
      </ul>
    </div>
  </nav>

  <script src="https://kit.fontawesome.com/e427689c7c.js" crossorigin="anonymous"></script>